trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd core
    npm install
  displayName: 'npm install'


- script: |
    cd core
    npm test
  displayName: 'npm test'
