parameters:
  - name: buildName
    type: string
  - name: extension
    type: string

steps:
  # Ensure required node version is installed
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops
  - task: NodeTool@0
    inputs:
      versionSpec: '>= 10.0.0'

  - download: current
    artifact: ui

  - script: |
      echo "Check in /"
      ls
      echo "*************"

      echo "Check in /ui dir"
      ls ui
      echo "*************"

      echo "copy files : cp -r ui/* app/assets/"
      cp -r ui/* app/assets/
      echo "*************"

      echo "Check in app/assets"
      ls app/assets
      echo "*************"

    displayName: 'ls app/assets'

  - script: |
      cd app
      yarn
    displayName: 'npm install'
#
#  - script: |
#      cd app
#      yarn make
#    displayName: 'Build electron app'
#
#  - task: CopyFiles@2
#    inputs:
#      sourceFolder: '$(System.DefaultWorkingDirectory)/app/out'
#      targetFolder: '$(Build.ArtifactStagingDirectory)'
#      flattenFolders: true
#      cleanTargetFolder: true
#      preserveTimestamp: true
#      contents: '**/*${{ parameters.extension }}'
#      overWrite: false
#
#  - task: PublishPipelineArtifact@1
#    inputs:
#      artifactName: ${{ parameters.buildName }}
#      targetPath: '$(Build.ArtifactStagingDirectory)'
#      artifactType: 'pipeline'
#      #fileSharePath: '\builds\${{ parameters.buildName }}'
