steps:
  # Ensure required node version is installed
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops
  - task: NodeTool@0
    inputs:
      versionSpec: '>= 10.0.0'

  - script: |
      cd ui
      npm i
    displayName: 'npm install'

  - script: |
      cd ui
      npm run build:prod
    displayName: 'npm run build'

  - publish: $(System.DefaultWorkingDirectory)/ui/dist
    artifact: ui-assets
